# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class YafaiCore < Formula
  desc "Core homebrew tap"
  homepage "https://github.com/YAFAI-Hub/core"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/YAFAI-Hub/core/releases/download/v0.0.2/yafai-core_darwin_x86_64.tar.gz"
      sha256 "fbdd9654114e37e8fc6f8d7e8be01fa9ef251f699795b5ac57fbe2d817db9c39"

      def install
        bin.install "yafai-core"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/YAFAI-Hub/core/releases/download/v0.0.2/yafai-core_darwin_arm64.tar.gz"
      sha256 "a32b0bf1990c0bd328156dde2307363d790ef0f8d40c893c7802705f6ee680cb"

      def install
        bin.install "yafai-core"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/YAFAI-Hub/core/releases/download/v0.0.2/yafai-core_linux_x86_64.tar.gz"
      sha256 "25f4180d69c77f3ddd739963a5aac93fcf621d53771fb8edb5283d3a5354a4eb"
      def install
        bin.install "yafai-core"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/YAFAI-Hub/core/releases/download/v0.0.2/yafai-core_linux_arm64.tar.gz"
      sha256 "a858726db106281e4a522191be34a6c92f19eb38d5a56fe6f9292630ffc51da6"
      def install
        bin.install "yafai-core"
      end
    end
  end
end
