# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class YafaiCore < Formula
  desc "Core homebrew tap"
  homepage "https://github.com/YAFAI-Hub/core"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/YAFAI-Hub/core/releases/download/v0.0.2/yafai-core_darwin_x86_64.tar.gz"
      sha256 "adf6b3bc5af9fb8532fa71ee095549da887a9c7d069a8929c528d27c4f043db0"

      def install
        bin.install "yafai-core"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/YAFAI-Hub/core/releases/download/v0.0.2/yafai-core_darwin_arm64.tar.gz"
      sha256 "203cb6f3e000cbb803a6a18060b06856a39fa069c2f5073e02e42f641ff483d2"

      def install
        bin.install "yafai-core"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/YAFAI-Hub/core/releases/download/v0.0.2/yafai-core_linux_x86_64.tar.gz"
      sha256 "4304a7db5e02a1640e640b6009e4b477810b7316045290681c8c2526c34a83f6"
      def install
        bin.install "yafai-core"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/YAFAI-Hub/core/releases/download/v0.0.2/yafai-core_linux_arm64.tar.gz"
      sha256 "1346fe6f61f3c6e0d088290c5f77797175f996c41243bcab075729fe67c28e28"
      def install
        bin.install "yafai-core"
      end
    end
  end
end
