# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class YafaiSkill < Formula
  desc "Core homebrew tap"
  homepage "https://github.com/YAFAI-Hub/skills"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/YAFAI-Hub/skills/releases/download/v0.0.1/yafai-skill_Darwin_x86_64.tar.gz"
      sha256 "be55907ce31c3c4a160c3f4729e05ba027de5f0e3161089fd0c68d15407480bf"

      def install
        bin.install "yafai-skill"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/YAFAI-Hub/skills/releases/download/v0.0.1/yafai-skill_Darwin_arm64.tar.gz"
      sha256 "2c45996c9382f7f715309b21111431092b5f18cd810eca5622dcec5c6157f3b7"

      def install
        bin.install "yafai-skill"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/YAFAI-Hub/skills/releases/download/v0.0.1/yafai-skill_Linux_x86_64.tar.gz"
        sha256 "6890809eef1aa5f332a90c02968613a5b09a34a2fe0fbfb8348759183453bd7c"

        def install
          bin.install "yafai-skill"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/YAFAI-Hub/skills/releases/download/v0.0.1/yafai-skill_Linux_arm64.tar.gz"
        sha256 "3cfdc51bb3c29429696578355558b10399db6e91bf3901c00b8420f07173a865"

        def install
          bin.install "yafai-skill"
        end
      end
    end
  end
end
