# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class YafaiSkill < Formula
  desc "Core homebrew tap"
  homepage "https://github.com/YAFAI-Hub/skills"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/YAFAI-Hub/skills/releases/download/v0.0.1/yafai-skill_Darwin_x86_64.tar.gz"
      sha256 "36efa684077cc32437dea4da2904a0e3ed2cfd8db048020c0fa4284e5c7e3f07"

      def install
        bin.install "yafai-skill"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/YAFAI-Hub/skills/releases/download/v0.0.1/yafai-skill_Darwin_arm64.tar.gz"
      sha256 "e5664d53a14e38d67b9601fdf0c0b4c45fa5ae74f18bcce9e2224a32f6dff801"

      def install
        bin.install "yafai-skill"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/YAFAI-Hub/skills/releases/download/v0.0.1/yafai-skill_Linux_x86_64.tar.gz"
        sha256 "3a5427ccfa14204fbf5c635ea9d9ff5e3820a0c4baccecbf95c3b87a62ab039d"

        def install
          bin.install "yafai-skill"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/YAFAI-Hub/skills/releases/download/v0.0.1/yafai-skill_Linux_arm64.tar.gz"
        sha256 "5f8d3de449a51babc25a1a69438025bdff19c09d15b0703ecaf7dcb79e9b9550"

        def install
          bin.install "yafai-skill"
        end
      end
    end
  end
end
