# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class YafaiCore < Formula
  desc "Core homebrew tap"
  homepage "https://github.com/YAFAI-Hub/core"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/YAFAI-Hub/core/releases/download/v0.0.1/yafai-core_Darwin_x86_64.tar.gz"
      sha256 "0d377bec3a79aaa0e6e9af72054d351e99805c787855420f36d6166a36d73b0c"

      def install
        bin.install "yafai-core"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/YAFAI-Hub/core/releases/download/v0.0.1/yafai-core_Darwin_arm64.tar.gz"
      sha256 "149694aab24b089821a0d5a224d6a3df6826704b413f21f711917cdd73040c83"

      def install
        bin.install "yafai-core"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/YAFAI-Hub/core/releases/download/v0.0.1/yafai-core_Linux_x86_64.tar.gz"
        sha256 "db079b6fe0d6442fbf2fa2ef2fc0c050411015367d9c52bc7f943b9ecc13f1e3"

        def install
          bin.install "yafai-core"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/YAFAI-Hub/core/releases/download/v0.0.1/yafai-core_Linux_arm64.tar.gz"
        sha256 "3c0785b40670f2345061199e444862269341993b313b2fdd5ea7f00a8f1fadba"

        def install
          bin.install "yafai-core"
        end
      end
    end
  end
end
