# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class YafaiSkill < Formula
  desc "Core homebrew tap"
  homepage "https://github.com/YAFAI-Hub/skills"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/YAFAI-Hub/skills/releases/download/v0.0.1/yafai-skill_Darwin_x86_64.tar.gz"
      sha256 "c6df4a7c5156509cce5f3b49f25410cd6292be178f4d91a0f18a4efe4c5572bd"

      def install
        bin.install "yafai-skill"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/YAFAI-Hub/skills/releases/download/v0.0.1/yafai-skill_Darwin_arm64.tar.gz"
      sha256 "731dc2ff2ecf991abe4a2cc9adf797193ee652cd02c0531b414a6c9dee8ea530"

      def install
        bin.install "yafai-skill"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/YAFAI-Hub/skills/releases/download/v0.0.1/yafai-skill_Linux_x86_64.tar.gz"
        sha256 "3fc68e9893d6b325fd96c738ec93f186382f818ba3c4ee9398e955dccfa80dbc"

        def install
          bin.install "yafai-skill"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/YAFAI-Hub/skills/releases/download/v0.0.1/yafai-skill_Linux_arm64.tar.gz"
        sha256 "5b3470379858213317a201537f758958a022b86933a57fc76f0fab09b926de0d"

        def install
          bin.install "yafai-skill"
        end
      end
    end
  end
end
